### ISSUE TITLE
JSON Quoting issues

### ISSUE THREAD

**Issue by bderenzi** [dimagi/commcare-export-json#1]
On importing, Snowflake is complaining about an errant comma. This seems to be from a quoting issue on the JSON export. Here's an example of a key-value pair that is likely causing the issue:

```
"appVersion": "CommCare ODK, version \\"2.20.0\\"(358089). App v135. CommCare Version 2.20. Build 348074, built on: March-27-2015",
```

**Comment by roboton** [comment]
Fixed in #4
