### ISSUE TITLE
Need to expose server flag 

### ISSUE THREAD

**Issue by bderenzi** [dimagi/commcare-export-json#3]
The data export tool defaults to the https://www.commcarehq.org production environment. This can be changed by using the [commcare-hq flag](https://github.com/dimagi/commcare-export/blob/d43db47538c44ebf7079389a7c9e0e6099219ab2/commcare_export/cli.py#L61). We need to expose this to be able to use the tool from different environments

**Comment by roboton** [comment]
Fixed in #4
